### ISSUE TITLE
Investigate - Parallel executions, locking

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-atlantis#2]
Investigate what to do when multiple comments are sent to Atlantis.

What about locking?

Will there be a need to resolve cold starts (eg, use GitHub -> SQS -> SNS -> Lambda -> Fargate) ?

**Comment by bryantbiggs** [comment]
@antonbabenko I think this is now handled natively by Atlantis with the following in the `atlantis.yaml`:

```yaml
version: 3

parallel_plan: true
parallel_apply: true
automerge: true

...
```
