### ISSUE TITLE
custom_environment_variables with ATLANTIS_REPO_CONFIG_JSON

### ISSUE THREAD

**Issue by ivanmartos** [terraform-aws-modules/terraform-aws-atlantis#68]
I'm having issues with setting env variables for the container. With the definition below
```
module "atlantis" {
  source  = "terraform-aws-modules/atlantis/aws"
  version = "~> v1.0"

  name             = "atlantis"
  atlantis_version = "v0.7.2"

  allow_repo_config = true
  policies_arn      = ["arn:aws:iam::aws:policy/AdministratorAccess"]

  # VPC
  vpc_id             = "XXXXXXXXX"                          
  cidr               = "XXXXXXXXX"
  azs                = ["XXXXXXXXX"]
  private_subnet_ids = ["XXXXXXXXX"]
  public_subnet_ids  = ["XXXXXXXXX"]

  # DNS (without trailing dot)
  route53_zone_name = "XXXXXX"

  # ACM (SSL certificate) - Specify ARN of an existing certificate or new one will be created and validated using Route53 DNS
  certificate_arn = "XXXXX"

  # Atlantis
  atlantis_github_user       = "X"
  atlantis_github_user_token = "XXXXX"
  atlantis_repo_whitelist    = ["github.com/XXXX/Xxxxxxxxx"]

  custom_environment_variables = [{
    name  = "ATLANTIS_REPO_CONFIG_JSON"
    value = "XXXXXX"
  }]
}
```

When I try to list the env variables in custom plan, I can't see any env variable named `ATLANTIS_REPO_CONFIG_JSON`.

Content of `atlantis.yaml` with custom workflow:
```
version: 3
automerge: true

projects:
  - name: XXXX
    dir: XXXX
    workspace: default
    terraform_version: v0.11.14
    autoplan:
      when_modified: ["*.tf", "../modules/**.tf"]
      enabled: true
    workflow: custom
workflows:
  custom:
    plan:
      steps:
        - run: env
        - init
        - plan
    apply:
      steps:
        - apply
```

My goal is to modify the default workflow using env variable `ATLANTIS_REPO_CONFIG_JSON` and json as argument as described here https://www.runatlantis.io/docs/server-side-repo-config.html#enabling-server-side-repo-config
