### ISSUE TITLE
Looking at the tf code, it looks like it's being passed in correctly. I'd like to fully eliminate the chances of the credentials being passed to Atlantis being incorrect. Can you verify what values were passed in to the container by creating a custom workflow that echo's out the environment variables?

### ISSUE THREAD

**Issue by trahloff** [terraform-aws-modules/terraform-aws-atlantis#95]
Looking at the tf code, it looks like it's being passed in correctly. I'd like to fully eliminate the chances of the credentials being passed to Atlantis being incorrect. Can you verify what values were passed in to the container by creating a custom workflow that echo's out the environment variables?

```yaml
# atlantis.yaml
version: 3
projects:
- dir: .
  workflow: echo
workflows:
  echo:
    plan:
      steps:
      - run: echo $ATLANTIS_BITBUCKET_USER
      - run: echo $ATLANTIS_BITBUCKET_TOKEN
```

_Originally posted by @lkysow in https://github.com/terraform-aws-modules/terraform-aws-atlantis/issues/54#issuecomment-499515606_
